- 의료 데이터이므로, 자세한 전처리 과정에 관한 코드는 공개하지 않습니다.

- 의료 데이터이므로, 데이터 정보가 노출되는 셀은 출력을 제거했습니다.
- 출력 길이가 쓸데 없이 긴 셀도 출력을 제거했습니다.

In [56]:
import pandas as pd
import numpy as np
from IPython.display import display
import sys
sys.path.append('/workspace/HRV')
from func import *

In [ ]:
df = pd.read_excel('final_data.xlsx')
df.drop(columns = ['Unnamed: 0'],inplace = True)
display(df.head(2))
print(df.shape) # (336, 54)

In [ ]:
print(df.isna().sum()) # '25-Hydroxy Vitamin D (D3/D2)' 에만 nan 값 존재

In [59]:
col_list = {'num_col' : [],
            'cat_col' : [],
            'cat_col_ord' : [],
            'label' : ['state_anx'],
            'drop_col' : []
            }

### ChartID	PersonalID 환자번호

In [60]:
print(df.shape[0])
print(len(set(df['ChartID'])))
print(len(set(df['PersonalID'])))
print(len(set(df['환자번호'])))
# 각 row별로 다른 환자에 대한 데이터

336
336
336
336


In [61]:
col_list['drop_col'].extend(['ChartID','PersonalID'])
col_list['drop_col'].extend(['환자번호'])
col_list['drop_col'].extend(['Date'])

### Age

In [62]:
check(df, 'Age',col_list)

(array([19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       72, 73, 83], dtype=int64), array([ 3,  2,  3,  2,  1,  1,  1,  2,  3,  2,  8,  4,  4,  4,  4, 10,  4,
        5,  7,  9,  9,  7,  5,  9, 13, 10,  8, 14, 10,  9, 11,  7, 10, 11,
       11,  9,  7,  6, 12, 11, 11,  8, 14,  4,  9,  4,  5,  3,  1,  2,  2,
        2,  2,  1], dtype=int64))
수치형변수입니다.
수치형 변수에 추가했습니다.
['Age']


### Sex

In [63]:
check(df, 'Sex',col_list)

(array([0, 1], dtype=int64), array([191, 145], dtype=int64))
cat_col에 추가했습니다.
['Sex']


### 측정센서

In [64]:
check(df, '측정센서',col_list)

(array(['ECG'], dtype=object), array([336], dtype=int64))
drop_col에 추가했습니다.
['ChartID', 'PersonalID', '환자번호', 'Date', '측정센서']


### 자율신경 활성도

In [65]:
check(df, '자율신경 활성도',col_list)

(array([ 50.  ,  54.29,  55.71,  61.43,  62.86,  63.33,  64.29,  65.71,
        67.14,  68.57,  70.  ,  71.43,  72.86,  74.  ,  74.29,  75.71,
        76.15,  76.67,  77.14,  77.69,  78.  ,  78.57,  79.33,  80.  ,
        80.77,  81.43,  82.  ,  82.86,  83.33,  83.85,  84.29,  84.67,
        85.71,  86.  ,  86.92,  87.14,  87.33,  88.46,  88.57,  88.67,
        90.  ,  91.54,  91.67,  91.82,  92.  ,  93.08,  93.33,  93.64,
        94.  ,  94.62,  95.  ,  95.45,  96.  ,  96.15,  96.67,  97.27,
        97.69,  98.  ,  98.33,  99.09,  99.23, 100.  , 100.77, 100.91,
       101.67, 102.  , 102.31, 102.73, 103.33, 103.85, 104.  , 104.55,
       105.  , 105.38, 106.36, 106.67, 106.92, 108.18, 108.33, 108.46,
       110.  , 114.  , 115.  , 116.67, 122.  , 126.  , 130.  , 131.43,
       132.67, 132.86, 134.  , 137.14, 138.57, 140.  , 142.31, 145.71,
       150.  ]), array([ 1,  1,  1,  1,  3,  1,  2,  2,  3,  2,  5,  1,  6,  2,  3,  5,  2,
        2, 10,  2,  1, 10,  2, 11,  2, 10,  3, 10,  1, 

### 자율신경 균형도

In [66]:
check(df, '자율신경 균형도',col_list)

(array([  0.  ,   1.79,   1.92,   2.78,   2.94,   3.13,   3.57,   3.85,
         5.56,   5.77,   5.88,   6.25,   7.14,   7.69,   8.82,   9.38,
         9.62,  11.54,  11.76,  12.5 ,  13.46,  13.89,  14.29,  14.71,
        15.38,  15.63,  16.07,  17.31,  17.86,  18.75,  19.23,  19.64,
        21.15,  21.88,  22.22,  23.08,  23.21,  25.  ,  26.47,  26.92,
        27.78,  28.13,  28.85,  30.36,  30.77,  31.25,  32.14,  32.35,
        32.69,  34.62,  35.71,  37.5 ,  38.24,  38.46,  40.38,  41.67,
        42.86,  43.75,  44.12,  44.23,  44.44,  46.15,  48.08,  50.  ,
        51.43,  51.47,  52.  ,  52.86,  53.23,  53.64,  55.  ,  56.  ,
        56.36,  57.14,  57.27,  57.81,  58.  ,  58.33,  58.57,  58.7 ,
        59.  ,  59.38,  59.65,  61.29,  62.5 ,  62.73,  63.04,  63.24,
        64.29,  65.  ,  65.22,  66.67,  67.  ,  67.19,  68.57,  69.  ,
        70.  ,  70.59,  71.74,  71.82,  75.  ,  77.17,  77.78,  78.57,
        80.  ,  83.33,  84.55,  85.71,  87.5 ,  88.89,  90.  ,  91.67,
     

### '스트레스 저항도', '스트레스 지수'

In [ ]:
check(df, '스트레스 저항도',col_list)

In [ ]:
check(df, '스트레스 지수',col_list)

### 피로도

In [69]:
check(df, '피로도',col_list)

(array([ 50.  ,  51.33,  54.29,  55.71,  58.57,  60.  ,  61.43,  62.86,
        64.29,  64.67,  66.  ,  67.33,  68.67,  70.  ,  76.67,  83.33,
        85.  ,  90.  ,  91.33,  91.54,  92.67,  93.08,  93.64,  94.  ,
        94.62,  95.  ,  95.33,  95.45,  96.15,  96.67,  97.14,  97.27,
        97.69,  98.  ,  99.23,  99.33, 100.  , 100.67, 101.43, 101.67,
       102.  , 102.31, 102.86, 103.33, 104.29, 104.67, 105.  , 105.38,
       105.71, 106.  , 106.67, 106.92, 107.14, 107.33, 108.18, 108.33,
       108.46, 108.67, 110.  , 111.43, 111.54, 111.67, 112.86, 113.08,
       113.33, 114.29, 114.62, 115.  , 115.71, 116.15, 116.67, 117.14,
       117.69, 118.33, 118.57, 119.23, 120.  , 120.77, 121.43, 121.67,
       122.31, 122.86, 123.33, 123.85, 124.29, 125.  , 125.38, 125.71,
       126.67, 126.92, 128.33, 128.46, 128.57, 130.  , 131.43, 132.67,
       132.86, 133.08, 134.  , 134.29, 134.62, 135.33, 135.71, 136.15,
       137.69, 140.  , 141.43, 142.  , 142.31, 143.85, 144.29, 145.38,
     

### 평균 심박동수

In [ ]:
check(df,'평균 심박동수', col_list)

### '심장 안정도','이상 심박동수'

In [16]:
check(df, '심장 안정도',col_list)

(array([ 50.  ,  51.18,  51.25,  51.33,  55.33,  55.88,  58.  ,  60.67,
        61.25,  61.76,  62.  ,  63.33,  63.75,  64.67,  65.  ,  66.47,
        67.5 ,  67.65,  68.67,  68.75,  70.  ,  71.54,  71.67,  71.82,
        73.64,  74.62,  75.  ,  76.15,  76.67,  77.69,  78.33,  79.09,
        79.23,  80.  ,  80.77,  80.91,  81.67,  82.31,  83.33,  83.85,
        85.  ,  85.38,  86.36,  86.67,  86.92,  88.33,  88.46,  90.  ,
        91.18,  91.25,  91.33,  91.43,  92.35,  92.5 ,  92.67,  93.53,
        93.75,  94.  ,  94.29,  94.71,  95.  ,  95.33,  95.71,  95.88,
        96.25,  96.67,  97.06,  97.14,  97.5 ,  98.  ,  98.57,  98.75,
        99.33,  99.41, 100.  , 100.59, 100.67, 101.25, 101.43, 101.76,
       102.  , 102.5 , 102.86, 102.94, 103.33, 103.75, 104.12, 104.29,
       104.67, 105.  , 105.29, 105.71, 106.  , 106.25, 106.47, 107.14,
       107.33, 107.5 , 108.57, 108.67, 108.75, 108.82, 110.  , 116.67,
       120.  , 123.33, 130.  , 131.18, 131.25, 131.33, 132.35, 132.67,
     

In [17]:
check(df, '이상 심박동수',col_list)

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  12,  14,  16,  34,
        47, 107], dtype=int64), array([296,  16,   5,   6,   1,   1,   1,   2,   2,   1,   1,   1,   1,
         1,   1], dtype=int64))
수치형변수입니다.
수치형 변수에 추가했습니다.
['Age', '자율신경 활성도', '자율신경 균형도', '스트레스 저항도', '스트레스 지수', '피로도', '평균 심박동수', '심장 안정도', '이상 심박동수']


### 'Sdnn', 'Psi', 'Tp', 'Vlf', 'Lf', 'Hf', 'LfNorm', 'HfNorm','Lf/Hf', 'Rmssd', 'Apen', 'Srd', 'Tsrd', 'Tp(ln)', 'Vlf(ln)', 'Lf(ln)','Hf(ln)'

In [ ]:
li = ['Sdnn', 'Psi', 'Tp', 'Vlf', 'Lf', 'Hf', 'LfNorm', 'HfNorm',
       'Lf/Hf', 'Rmssd', 'Apen', 'Srd', 'Tsrd', 'Tp(ln)', 'Vlf(ln)', 'Lf(ln)',
       'Hf(ln)']
for i in li:
    check(df, i,col_list)

### 수진당시나이

In [19]:
check(df, '수진당시나이',col_list)

(array([19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       72, 73, 83], dtype=int64), array([ 3,  2,  3,  2,  1,  1,  1,  2,  3,  2,  8,  4,  4,  4,  4, 10,  4,
        5,  7,  9,  9,  7,  5,  9, 13, 10,  8, 14, 10,  9, 11,  7, 10, 11,
       11,  9,  7,  6, 12, 11, 11,  8, 14,  4,  9,  4,  5,  3,  1,  2,  2,
        2,  2,  1], dtype=int64))
수치형변수입니다.
수치형 변수에 추가했습니다.
['Age', '자율신경 활성도', '자율신경 균형도', '스트레스 저항도', '스트레스 지수', '피로도', '평균 심박동수', '심장 안정도', '이상 심박동수', 'Sdnn', 'Psi', 'Tp', 'Vlf', 'Lf', 'Hf', 'LfNorm', 'HfNorm', 'Lf/Hf', 'Rmssd', 'Apen', 'Srd', 'Tsrd', 'Tp(ln)', 'Vlf(ln)', 'Lf(ln)', 'Hf(ln)', '수진당시나이']


In [20]:
li = ['PSS', 'AB', 'FSS', 'CES'
    #   , 'state_anx' 
      , 'BFI']
for i in li:
    check(df, i, col_list)

(array([0, 1], dtype=int64), array([  7, 329], dtype=int64))
cat_col에 추가했습니다.
['Sex', 'PSS']
(array([0, 1], dtype=int64), array([241,  95], dtype=int64))
cat_col에 추가했습니다.
['Sex', 'PSS', 'AB']
(array([0, 1], dtype=int64), array([180, 156], dtype=int64))
cat_col에 추가했습니다.
['Sex', 'PSS', 'AB', 'FSS']
(array([0, 1], dtype=int64), array([214, 122], dtype=int64))
cat_col에 추가했습니다.
['Sex', 'PSS', 'AB', 'FSS', 'CES']
(array([0, 1], dtype=int64), array([167, 169], dtype=int64))
cat_col에 추가했습니다.
['Sex', 'PSS', 'AB', 'FSS', 'CES', 'BFI']


### '25-Hydroxy Vitamin D (D3/D2)' -> 결측값 존재 : 사용하지 않겠음

In [21]:
check(df,'25-Hydroxy Vitamin D (D3/D2)',col_list)

(array([nan]), array([336], dtype=int64))
수치형변수입니다.
drop_col에 추가했습니다.
['ChartID', 'PersonalID', '환자 번호', '측정센서', '25-Hydroxy Vitamin D (D3/D2)']


### '25-Hydroxy Vitamin D (Total)','Albumin', 'Free T4', 'GGT', 'GOT (AST)', 'GPT (ALT)', 'Glucose', 'Hb','HbA1c-NGSP', 'LDL-Cholesterol', 'TSH', 'TG', 'eGFR'

In [ ]:
li = ['25-Hydroxy Vitamin D (Total)','Albumin', 'Free T4', 'GGT', 'GOT (AST)', 'GPT (ALT)', 'Glucose', 'Hb','HbA1c-NGSP', 'LDL-Cholesterol', 'TSH', 'TG', 'eGFR']
for i in li:
    check(df,i,col_list)

### 등록번호 확인

In [29]:
print(len(set(df['등록번호_확인'])))
print(df.shape[0])

336
336


In [ ]:
check(df,'등록번호_확인', col_list)

### 변수 분류된 결과 col_list

In [30]:
col_list

{'num_col': ['Age',
  '자율신경 활성도',
  '자율신경 균형도',
  '스트레스 저항도',
  '스트레스 지수',
  '피로도',
  '평균 심박동수',
  '심장 안정도',
  '이상 심박동수',
  'Sdnn',
  'Psi',
  'Tp',
  'Vlf',
  'Lf',
  'Hf',
  'LfNorm',
  'HfNorm',
  'Lf/Hf',
  'Rmssd',
  'Apen',
  'Srd',
  'Tsrd',
  'Tp(ln)',
  'Vlf(ln)',
  'Lf(ln)',
  'Hf(ln)',
  '수진당시나이',
  '25-Hydroxy Vitamin D (Total)',
  'Albumin',
  'Free T4',
  'GGT',
  'GOT (AST)',
  'GPT (ALT)',
  'Glucose',
  'Hb',
  'HbA1c-NGSP',
  'LDL-Cholesterol',
  'TSH',
  'TG',
  'eGFR'],
 'cat_col': ['Sex', 'PSS', 'AB', 'FSS', 'CES', 'BFI'],
 'cat_col_ord': [],
 'label': ['state_anx'],
 'drop_col': ['ChartID',
  'PersonalID',
  '환자 번호',
  '측정센서',
  '25-Hydroxy Vitamin D (D3/D2)',
  '등록번호_확인']}

In [ ]:
df.drop(columns=col_list['drop_col'],inplace = True)

In [ ]:
df.head(5)

### 이상심박동수

In [43]:
set(df['이상 심박동수'])

{0, 1, 2, 3, 4, 5, 6, 7, 8, 12, 14, 16, 34, 47, 107}

In [ ]:
res = df[[ '평균 심박동수',  '심장 안정도','이상 심박동수']]
display(res[res['이상 심박동수'] == 0])
display(res[res['이상 심박동수'] == 1])
display(res[res['이상 심박동수'] == 107])

In [ ]:
df.drop(columns='이상 심박동수',inplace = True)
df.head(2)

In [75]:
col_list['num_col'].remove('이상 심박동수')

In [51]:
df.to_csv('data1.csv',index = False)

In [80]:
%store col_list 
# 다른 코드파일에서 불러올 수 있게 변수 저장

Stored 'col_list' (dict)
